### ISSUE TITLE
AI not spawning on Chernarus 2020

### ISSUE THREAD

**Issue by ehylla93** [Ghostrider-DbD-/blckeagles-revisited-RC#174]
22:11:10 "[blckeagls] :: Timstamp  |Dynamic Missions Running 4 | Vehicles 0 | Groups 0 | Missions Run 0 | Server FPS 44.9438 | Server Uptime 17 Min"
22:11:10 "[blckeagls] :: count diag_activeSQFScripts 31 | Threads [spawned 23, execVM 8] | monitorThreads 0"
22:11:10 "[blckeagls] :: file  | running true"
22:11:10 "[blckeagls] :: file mpmissions\__cur_mp.cup_chernarus_A3\ЭШСЖЩК\	\	 \		\			\\ЭЩЧАП\ЧЧУИЖ\	 | running true"
22:11:10 "[blckeagls] :: file mpmissions\__cur_mp.cup_chernarus_A3\ДЭРЯЗЪ\ 	\ФУЖИ\ 	 | running true"
22:11:10 "[blckeagls] :: file A3\Structures_F\Wrecks\Scripts\Wreck_Heli_Attack_01.sqf | running true"
22:11:10 "[blckeagls] :: file A3\Structures_F\Wrecks\Scripts\Wreck_Heli_Attack_01.sqf | running true"
22:11:10 "[blckeagls] :: file A3\Structures_F\Wrecks\Scripts\Wreck_Heli_Attack_01.sqf | running true"
22:11:10 "[blckeagls] :: file A3\Structures_F\Wrecks\Scripts\Wreck_Heli_Attack_01.sqf | running true"
22:11:10 "[blckeagls] :: file A3\Structures_F\Wrecks\Scripts\Wreck_Heli_Attack_01.sqf | running true"
22:11:10 "[blckeagls] :: file a3\modules_f_curator\curator\functions\fn_moduleCurator.sqf [BIS_fnc_moduleCurator] | running true"
22:11:10 "[blckeagls] :: file mpmissions\__cur_mp.cup_chernarus_A3\			\НЗЗХ\		 | running true"
22:11:10 "[blckeagls] :: file a3_infiSTAR_vision\functions\fn_zeus_check.sqf [a3_infiSTAR_vision_fnc_zeus_check] | running true"
22:11:10 "[blckeagls] :: file exile_server\code\ExileServer_system_thread_initialize.sqf | running true"
22:11:10 "[blckeagls] :: file a3_vemf_reloaded\sqf\missionTimer.sqf | running true"
22:11:10 "[blckeagls] :: file a3_vemf_reloaded\sqf\REMOTEguard.sqf | running true"
22:11:10 "[blckeagls] :: file q\addons\custom_server\Compiles\Functions\GMS_fnc_mainThread.sqf | running true"
22:11:10 "[blckeagls] :: file A3XAI\scripts\A3XAI_serverMonitor.sqf | running true"
22:11:10 "[blckeagls] :: file A3XAI\compile\A3XAI_group_functions\A3XAI_addGroupManager.sqf | running true"
22:11:10 "[blckeagls] :: file A3XAI\compile\A3XAI_group_functions\A3XAI_addGroupManager.sqf | running true"
22:11:10 "[blckeagls] :: file A3XAI\compile\A3XAI_group_functions\A3XAI_addGroupManager.sqf | running true"
22:11:10 "[blckeagls] :: file A3XAI\compile\A3XAI_group_functions\A3XAI_addGroupManager.sqf | running true"
22:11:10 "[blckeagls] :: file A3XAI\compile\A3XAI_group_functions\A3XAI_addGroupManager.sqf | running true"
22:11:10 "[blckeagls] :: file a3_vemf_reloaded\fn\fn_waitForPlayers.sqf [VEMFr_fnc_waitForPlayers] | running true"
22:11:10 "[blckeagls] :: file A3XAI\compile\A3XAI_group_functions\A3XAI_addGroupManager.sqf | running true"
22:11:10 "[blckeagls] :: file A3XAI\compile\A3XAI_group_functions\A3XAI_addGroupManager.sqf | running true"
22:11:10 "[blckeagls] :: file A3XAI\compile\A3XAI_group_functions\A3XAI_addGroupManager.sqf | running true"
22:11:10 "[blckeagls] :: file a3_vemf_reloaded\fn\fn_waitForPlayers.sqf [VEMFr_fnc_waitForPlayers] | running true"
22:11:10 "[blckeagls] :: file exile_server\code\ExileServer_system_event_drugs_start.sqf | running true"
22:11:10 "[blckeagls] :: file exile_server\code\ExileServer_system_event_farming_start.sqf | running true"
22:11:10 "[blckeagls] :: file A3XAI\compile\A3XAI_unit_spawning\A3XAI_processRespawn.sqf | running true"
22:11:10 "[blckeagls] :: file A3XAI\compile\A3XAI_unit_spawning\A3XAI_despawn_static.sqf | running true"
22:11:10 "[blckeagls] :: file A3\functions_f\Effects\fn_effectKilledAirDestruction.sqf [BIS_fnc_effectKilledAirDestruction] | running true"

**Comment by ehylla93** [comment]
Used the latest revision, just changed configs to current values.

**Comment by Ghostrider-DbD-** [comment]
that is so you can see what scripts are running on the server, and is more for debugging purposes. If it runs bug free I'll push a new build that removes some of those logs. With the current way Arma writes to logs using asyncryonous logging it should not cause too much of a server performance hit.

**Comment by ehylla93** [comment]
Yep, but thats the only stuff I have.

The missions are spawning fine, but only the AI is not spawning.

Ghostrider [GRG] <notifications@github.com> schrieb am Sa., 21. Nov. 2020,
23:44:

**Comment by Ghostrider-DbD-** [comment]
Please be sure to update to Build 237. There was a bug in 235 that prevented missions from being triggered.

**Comment by ehylla93** [comment]
Issue seems to be fixed, but there are two new issues:

- AI spawn without main guns, only pistols
- mission crates wont appear

15:50:03 Error in expression <alive _assetSpawned))) then
{
if (count _missionLootBoxes > 0) then
{
_crates = >
15:50:03   Error position: <_missionLootBoxes > 0) then
{
_crates = >
15:50:03   Error Undefined variable in expression: _missionlootboxes
15:50:03 File q\addons\custom_server\Compiles\Missions\GMS_fnc_monitorInitializedMissions.sqf..., line 546

**Comment by Ghostrider-DbD-** [comment]
OK I will take a look, thank you.

**Comment by Ghostrider-DbD-** [comment]
Found the cause of the error with _missionlootboxes.
Working on a fix for the missing primary weapons; I think I know the cause.

**Comment by ehylla93** [comment]
https://github.com/Ghostrider-DbD-/blckeagles-revisited-RC/issues/153

**Comment by Ghostrider-DbD-** [comment]
Fixed the problem with the _missionLootBoxes (needs testing) and missing primary weapons (Confirmed)

**Comment by Ghostrider-DbD-** [comment]
Build 153 is so far behind the current one they really are not comparable. Thanks though for digging through the problem list.

**Comment by ehylla93** [comment]
Problem seems partially solved:

18:28:44 Error in expression < && (alive _assetSpawned))) then
{
if !(_missionLootBoxes isEqualTo []) then
{
_>
18:28:44   Error position: <_missionLootBoxes isEqualTo []) then
{
_>
18:28:44   Error Undefined variable in expression: _missionlootboxes
18:28:44 File q\addons\custom_server\Compiles\Missions\GMS_fnc_monitorInitializedMissions.sqf..., line 546
18:28:44 "[blckeagls] :: Mission Completed | _coords [6297.51,8544.76,0] : _markerClass RedMarker :  _markerMissionName Medical Camp"

- crates not spawning atMissionEndAir but atMissionEndGround
- missions are spawning in other GMs missions > maybe there should be a check

also it seems that blck_useConfigsGeneratedLoadouts is not working correct - AI still spawns with vanilla stuff

**Comment by Ghostrider-DbD-** [comment]
OK Thanks, will investigate further.

**Comment by Ghostrider-DbD-** [comment]
what mode are you using for the time of crate spawning?

**Comment by ehylla93** [comment]
I use atMissionEndAir.

And it seems there is a problem regarding blck_useTimeAcceleration? Time resets to 10am but blck_useTimeAcceleration is false. Can you confirm that this is related to GMS or another source?

**Comment by Ghostrider-DbD-** [comment]
I will look at the time as well.
Thanks for the reports by the way - they are very helpful.

**Comment by Ghostrider-DbD-** [comment]
I see the issues go deeper .. more work to do ..  crate spawn and para spawn timing is messed up now.

**Comment by Ghostrider-DbD-** [comment]
In my testing with build 238 the crate spawn and crate loading work perfectly for all possible setting.

**Comment by ehylla93** [comment]
Can you update it then to latest build? Want to test it also.

Thanks for your fast response! :)

**Comment by Ghostrider-DbD-** [comment]
blckeagls does have a module to manage time acceleration.
To disable this, set 	blck_useTimeAcceleration = false; (blck_config.sqf, line 58)
